### ISSUE TITLE
Title animation?

### ISSUE THREAD

**Issue by ItzFel** [AyzrixYTB/Scoreboard#1]

**Comment by Steelfri** [comment]
on est qnd même sur mcpe oubliez pas

**Comment by ErwanScraft** [comment]
![Screenshot_2021-07-17-21-20-25-228_com android chrome](https://user-images.githubusercontent.com/72255518/126040005-85a935bb-fc1f-4421-be6a-631631a09a11.jpg)

why when I enter the server internal server error

**Comment by ErwanScraft** [comment]
![IMG_20210717_212333](https://user-images.githubusercontent.com/72255518/126040089-656e4f8a-fd17-42d5-929b-d7b68688a746.jpg)

why when i enter the server it kicks internal server error

**Comment by AyzrixYTB** [comment]
> ![IMG_20210717_212333](https://user-images.githubusercontent.com/72255518/126040089-656e4f8a-fd17-42d5-929b-d7b68688a746.jpg)
> 
> why when i enter the server it kicks internal server error

You have a seriously problem.... "ScoreHUD" are you dumb ?
