### ISSUE TITLE
Server lags

### ISSUE THREAD

**Issue by Willtom999** [AyzrixYTB/Scoreboard#3]
Is it normal that the server lag when we put the plugin?

**Comment by AyzrixYTB** [comment]
Hello, the problem is not with the plugin. All the scoreboards are slightly lagging the servers, it is up to you to manage the update time of the scoreboard to remedy this and to have a good machine.

**Comment by Willtom999** [comment]
Donc sa se joue sur les ticks

**Comment by AyzrixYTB** [comment]
Yes, I advise you to put between 5 and 10 seconds (100/200 ticks).

**Comment by Willtom999** [comment]
ok

**Comment by Willtom999** [comment]
Thanks
