### ISSUE TITLE
Internal server eror

### ISSUE THREAD

**Issue by ErwanScraft** [AyzrixYTB/Scoreboard#7]
When I log into the server, I was immediately bounced off by an internal server error when I used this plugin.

![Screenshot_2021-07-31-16-50-26-998_com android chrome](https://user-images.githubusercontent.com/72255518/127736196-f042f481-7adf-4818-a1f4-28d370e2a6aa.jpg)
![Screenshot_2021-07-31-16-49-50-963_com foxdebug acode](https://user-images.githubusercontent.com/72255518/127736206-f52ffb0a-4dbe-4092-b087-d3b7605715c6.jpg)

**Comment by AyzrixYTB** [comment]
That's not the Scoreboard plugin but "ExtendedBlocks"
