### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by chisi21** [AyzrixYTB/Scoreboard#8]
Make format money like
1000  = 1k
100.000 = 100k 
Etc
Thanks :D

**Comment by AyzrixYTB** [comment]
1000 = 1k
10000 = 10k
100000 = 100k
1000000 = 1M
10000000 = 10M
100000000 = 100M
1000000000 = 1B
10000000000 = 10B
100000000000 = 100B
1000000000000 = 1q
10000000000000 = 10q
100000000000000 = 100q
1000000000000000 = 1Q
10000000000000000 = 10Q
100000000000000000 = 100Q
1000000000000000000 = 1s
10000000000000000000 = 10s
100000000000000000000 = 100s
1000000000000000000000 = 1S
10000000000000000000000 = 10S
100000000000000000000000 = 100S

Just put "convert_money"' on true in the new config ! Thanks you for your suggestion

**Comment by chisi21** [comment]
> 1000 = 1k
> 10000 = 10k
> 100000 = 100k
> 1000000 = 1M
> 10000000 = 10M
> 100000000 = 100M
> 1000000000 = 1B
> 10000000000 = 10B
> 100000000000 = 100B
> 1000000000000 = 1q
> 10000000000000 = 10q
> 100000000000000 = 100q
> 1000000000000000 = 1Q
> 10000000000000000 = 10Q
> 100000000000000000 = 100Q
> 1000000000000000000 = 1s
> 10000000000000000000 = 10s
> 100000000000000000000 = 100s
> 1000000000000000000000 = 1S
> 10000000000000000000000 = 10S
> 100000000000000000000000 = 100S
> 
> Just put "convert_money"' on true in the new config ! Thanks you for your suggestion

Thank u :D
